### ISSUE TITLE
Ukol lekce #7

### ISSUE THREAD

**Issue by MKuliskova** [MKuliskova/python-012021#7]
@kkukpostcz
Ahoj, prosim o opravu ukolu z lekce 7. Dekuji :-)

**Comment by kkukpostcz** [comment]
Ahoj,
30. úkol : 1 bod
super
31. úkol : 1 bod
super
32. úkol : 1 bod
super
33. úkol : 1 bod
super
34. úkol : 1 bod
super
Měj se Aleš
