### ISSUE TITLE
Ukol lekce #8

### ISSUE THREAD

**Issue by MKuliskova** [MKuliskova/python-012021#8]
@kkukpostcz
Ahoj, prosim o opravu ukolu z lekce 8. Dekuji :-)

**Comment by kkukpostcz** [comment]
Ahoj,

36. úkol : 1 bod
super
37. úkol : 1 bod
super
38. úkol : 1 bod
super
39. úkol : 1 bod
super
40. úkol : 1 bod
super
Měj se
Aleš
